name: mlkit_document_scanner_example
description: "Demonstrates how to use the mlkit_document_scanner plugin."
publish_to: 'none'

environment:
  sdk: ">=3.9.2"
  flutter: ">=3.35.6"
  
dependencies:
  flutter:
    sdk: flutter

  mlkit_document_scanner:
    path: ../
  
  syncfusion_flutter_pdfviewer: ^31.2.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
