name: mlkit_document_scanner
description: Flutter plugin bringing MLKit Document Scanner to Flutter. Available only for Android.
version: 0.0.12
repository: https://github.com/sunderee/mlkit-document-scanner

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^6.0.0

topics:
  - machine-learning
  - mlkit
  - document-scanner
  - mlkit-document-scanner

flutter:
  plugin:
    platforms:
      android:
        package: com.peteralexbizjak.mlkit_document_scanner
        pluginClass: MlkitDocumentScannerPlugin
